import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "./components/Header"; // Import the Header component

const girlroy = localFont({
  src: [
    {
      path: "./fonts/Gilroy-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/Gilroy-Light.woff2",
      weight: "300",
      style: "light",
    },
    {
      path: "./fonts/Gilroy-Medium.woff2",
      weight: "600",
      style: "medium",
    },
    {
      path: "./fonts/Gilroy-Bold.woff2",
      weight: "700",
      style: "bold",
    },
    {
      path: "./fonts/Gilroy-Heavy.woff2",
      weight: "900",
      style: "heavy",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${girlroy.className} antialiased`}>
        <Header /> {/* Ensure Header does not use browser-specific code */}
        {children}
      </body>
    </html>
  );
}
